name: Build Pixel 8 Pro Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl zip unzip git python3

    - name: Install Bazel
      run: |
        # Download bazelisk directly
        curl -L -o bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-linux-amd64
        chmod +x bazelisk
        sudo mv bazelisk /usr/local/bin/bazel

testKernelSU()
{
	if [[ $(ksud -V 2>&1 | grep "not found" | wc -c) -eq 0 ]]; then #KSU installed
    	if [[ $(pm list packages | grep $PKGNAME | wc -c) -eq 0 ]]; then #PixelXpert NOT installed yet
    		ui_print ''
    		ui_print '*******************************'
    		ui_print 'KernelSU binaries found!'
    		ui_print ''
    		ui_print '                CAUTION!:'
    		ui_print 'Before installation, you MUST disable'
    		ui_print '"Unmount modules by default"'
    		ui_print 'Otherwise, your device will fall into BOOTLOOP!'
    		ui_print ''
    		ui_print 'Do you wish to continue?'
    		ui_print 'Volume Up: Continue'
    		ui_print 'Volume Down: Abort'
    		if [[ "$(getevent -l | grep -m 1 KEY_VOLUME)" == *"VOLUMEDOWN"* ]]; then
    			abort 'Installation cancelled'
    		fi;
    	fi;
    fi;
}

testKernelSU

prepareSQL

ui_print ''
ui_print ''

grantRootApps


    - name: Setup Build Environment
      run: |
        WORKSPACE_DIR=$(pwd)
        echo "Current directory: $WORKSPACE_DIR"
        mkdir -p tools
        echo "Copying bazel to tools directory"
        cp /usr/local/bin/bazel tools/
        chmod +x tools/bazel
        echo "Tools directory contents:"
        ls -la tools/
        echo "Testing bazel directly:"
        tools/bazel version
        echo "PATH=$WORKSPACE_DIR/tools:$PATH" >> $GITHUB_ENV

    - name: Prepare Kernel Source
      run: |
        # Save current directory
        WORKSPACE_DIR=$(pwd)
        echo "Workspace directory: $WORKSPACE_DIR"
        
        # Save tools
        cp -r tools /tmp/tools_backup
        echo "Tools backed up to /tmp/tools_backup"
        
        # Create temp directory for clone
        TEMP_DIR=$(mktemp -d)
        echo "Created temp directory: $TEMP_DIR"
        
        # Clone kernel source
        echo "Cloning kernel source..."
        git clone https://gitlab.hentaios.com/hentaios-gs-6.x/kernel_devices_google_shusky.git "$TEMP_DIR"
        cd "$TEMP_DIR"
        echo "Checking out Vallhound branch..."
        git checkout Vallhound
        echo "Updating submodules..."
        git submodule update --init --recursive
        
        echo "Temp directory contents:"
        ls -la "$TEMP_DIR"
        
        # Clean workspace directory
        cd "$WORKSPACE_DIR"
        echo "Cleaning workspace directory..."
        rm -rf * .[!.]* ..?*
        
        # Move kernel source
        echo "Moving kernel source to workspace..."
        mv "$TEMP_DIR"/* "$TEMP_DIR"/.[!.]* "$WORKSPACE_DIR"/ 2>/dev/null || true
        
        # Restore tools
        echo "Restoring tools..."
        cp -r /tmp/tools_backup tools
        
        # Clean up
        rm -rf "$TEMP_DIR"
        
        echo "Final workspace contents:"
        ls -la
        
        echo "Checking for husky build script:"
        if [ -f vendor/build_shusky.sh ]; then
          echo "build_shusky.sh exists"
          cat vendor/build_shusky.sh
        else
          echo "ERROR: build_shusky.sh not found!"
          exit 1
        fi

    - name: Build Kernel
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Tools directory contents:"
        ls -la tools/
        if [ ! -f build_shusky.sh ]; then
          echo "ERROR: build_shusky.sh not found!"
          exit 1
        fi
        chmod +x vendor/build_shusky.sh
        ./build_shusky.sh
PKGNAME="sh.siava.pixelxpert"
PKGPATH="/system/priv-app/PixelXpert/PixelXpert.apk"
LSPDDBPATH="/data/adb/lspd/config/modules_config.db"
MAGISKDBPATH="/data/adb/magisk.db"

prepareSQL(){
	unzip $ZIPFILE sqlite3 -d $TMPDIR/ > /dev/null
	chmod +x $TMPDIR/sqlite3

	SQLITEPATH="$TMPDIR/sqlite3"
}

# runSQL "database path" "command" - then you can use $SQLRESULT to read the outcome
runSQL(){
	SQLRESULT=$($SQLITEPATH $DBPATH "$CMD")
	
}

#grant silent root access to given UID
grantRootUID(){
	DBPATH=$MAGISKDBPATH
	
	#new record - older magisk compatibility
	CMD="insert
	
	
    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-artifacts
        path: |
          out/mixed/dist/*
          bazel-bin/**/*.ko
          bazel-bin/**/*.img
