name: Cleanup Workflow Runs

on:
  # Run daily at midnight UTC; adjust the cron as needed.
  schedule:
    - cron: '0 0 * * *'
  # Allow manual triggering.
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up ended workflow runs
        uses: ridedott/workflow-run-cleanup-action@v1
        with:
          # Use the automatically provided GitHub token.
          github_token: ${{ secrets.GITHUB_TOKEN }}
