name: Cleanup Workflow Runs

on:
  # Run daily at midnight UTC; adjust the cron schedule as needed.
  schedule:
    - cron: '0 0 * * *'
  # Allow manual triggering.
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up ended workflow runs
        uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: 'FALSE'
        # Optional: Prevent running on tags or master branch if not desired.
        if: "!startsWith(github.ref, 'refs/tags/') && github.ref != 'refs/heads/master'"
