name: Build Pixel 8 Pro Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl zip unzip git python3

    - name: Install Bazel
      run: |
        # Download bazelisk directly
        curl -L -o bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-linux-amd64
        chmod +x bazelisk
        sudo mv bazelisk /usr/local/bin/bazel

    - name: Setup Build Environment
      run: |
        WORKSPACE_DIR=$(pwd)
        echo "Current directory: $WORKSPACE_DIR"
        mkdir -p tools
        echo "Copying bazel to tools directory"
        cp /usr/local/bin/bazel tools/
        chmod +x tools/bazel
        echo "Tools directory contents:"
        ls -la tools/
        echo "Testing bazel directly:"
        tools/bazel version
        echo "PATH=$WORKSPACE_DIR/tools:$PATH" >> $GITHUB_ENV

    - name: Prepare Kernel Source
      run: |
        echo "Current directory before clone: $(pwd)"
        # Create tools directory if it doesn't exist
        mkdir -p tools
        # Copy bazel to tools directory again to ensure it exists
        cp /usr/local/bin/bazel tools/
        chmod +x tools/bazel
        echo "Saving tools directory"
        cp -r tools tools_backup
        rm -rf * .[!.]*
        echo "Restoring tools directory"
        mv tools_backup tools
        echo "Cloning kernel source"
        git clone https://gitlab.hentaios.com/hentaios-gs-6.x/kernel_devices_google_shusky.git .
        git checkout Vallhound
        git submodule update --init --recursive
        echo "Final directory structure:"
        ls -la
        echo "Tools directory contents:"
        ls -la tools/

    - name: Build Kernel
      run: |
        echo "Current directory: $(pwd)"
        echo "PATH: $PATH"
        echo "Tools directory contents:"
        ls -la tools/
        chmod +x build_shusky.sh
        ./build_shusky.sh

    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-artifacts
        path: |
          out/mixed/dist/*
          bazel-bin/**/*.ko
          bazel-bin/**/*.img
