name: Build Pixel 8 Pro Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl zip unzip git python3

    - name: Install Bazel
      run: |
        curl -L -o bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-linux-amd64
        chmod +x bazelisk
        sudo mv bazelisk /usr/local/bin/bazel

    - name: Setup Build Environment
      run: |
        WORKSPACE_DIR=$(pwd)
        mkdir -p tools
        cp /usr/local/bin/bazel tools/
        chmod +x tools/bazel
        echo "PATH=$WORKSPACE_DIR/tools:$PATH" >> $GITHUB_ENV

    - name: Prepare Kernel Source
      run: |
        WORKSPACE_DIR=$(pwd)
        TEMP_DIR=$(mktemp -d)
        # Clone kernel source
        git clone https://gitlab.hentaios.com/hentaios-gs-6.x/kernel_devices_google_shusky.git "$TEMP_DIR"
        cd "$TEMP_DIR"
        git checkout Vallhound
        git submodule update --init --recursive
        
        # Clean workspace and move kernel source
        cd "$WORKSPACE_DIR"
        rm -rf * .[!.]* ..?*
        mv "$TEMP_DIR"/* "$TEMP_DIR"/.[!.]* "$WORKSPACE_DIR"/ 2>/dev/null || true
        
        # Create workspace_status.sh
        mkdir -p tools
        cat > tools/workspace_status.sh << 'EOF'
        #!/bin/bash
        echo "STABLE_BUILD_SCM_REVISION $(git rev-parse HEAD)"
        echo "BUILD_TIMESTAMP $(date +%s)"
        EOF
        chmod +x tools/workspace_status.sh
        
        # Clean up
        rm -rf "$TEMP_DIR"

    - name: Build Kernel
      run: |
        chmod +x build_shusky.sh
        ./build_shusky.sh

    - name: Upload Kernel Artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: kernel-artifacts
        path: |
          out/mixed/dist/*
          bazel-bin/**/*.ko
          bazel-bin/**/*.img
