name: Build Pixel 8 Pro Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl zip unzip git python3

    - name: Install Bazel
      run: |
        curl -L -o bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-linux-amd64
        chmod +x bazelisk
        sudo mv bazelisk /usr/local/bin/bazel

    - name: Clone Kernel Source
      run: |
        git clone https://gitlab.hentaios.com/hentaios-gs-6.x/kernel_devices_google_shusky.git
        cd kernel_devices_google_shusky
        git checkout Vallhound
        git submodule update --init --recursive

    - name: Setup Workspace Status Script
      run: |
        mkdir -p kernel_devices_google_shusky/tools
        cat > kernel_devices_google_shusky/tools/workspace_status.sh << 'EOF'
        #!/bin/bash
        echo "STABLE_BUILD_SCM_REVISION $(git rev-parse HEAD)"
        echo "BUILD_TIMESTAMP $(date +%s)"
        EOF
        chmod +x kernel_devices_google_shusky/tools/workspace_status.sh

    - name: Build Kernel
      working-directory: ./kernel_devices_google_shusky
      run: |
        chmod +x build_shusky.sh
        ./build_shusky.sh

    - name: Upload Kernel Artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: kernel-artifacts
        path: |
          kernel_devices_google_shusky/out/mixed/dist/*
          kernel_devices_google_shusky/bazel-bin/**/*.ko
          kernel_devices_google_shusky/bazel-bin/**/*.img
