name: Build Pixel 8 Pro Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl zip unzip git python3

    - name: Install Bazel via Bazelisk
      run: |
        curl -L -o bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-linux-amd64
        chmod +x bazelisk
        sudo mv bazelisk /usr/local/bin/bazel

    - name: Clone Kernel Source
      run: |
        git clone https://gitlab.hentaios.com/hentaios-gs-6.x/kernel_devices_google_shusky.git
        cd kernel_devices_google_shusky
        git checkout Vallhound
        git submodule update --init --recursive --depth=1

    - name: Configure Bazel Environment
      working-directory: ./kernel_devices_google_shusky
      run: |
        echo "8.0.1" > .bazelversion
        cat << EOF >> .bazelrc
        build --stamp
        build --enable_platform_specific_config
        build --config=linux
        try-import %workspace%/device.bazelrc
        EOF

    - name: Setup Bazel Binary # NEW CRITICAL STEP
      working-directory: ./kernel_devices_google_shusky
      run: |
        mkdir -p tools
        # Copy system-installed bazel to project tools directory
        cp /usr/local/bin/bazel tools/
        chmod +x tools/bazel
        # Verify existence
        ls -l tools/bazel

    - name: Build Kernel
      working-directory: ./kernel_devices_google_shusky
      run: |
        mkdir -p tools
        cat > tools/workspace_status.sh << 'EOF'
        #!/bin/bash
        echo "STABLE_BUILD_SCM_REVISION $(git rev-parse HEAD)"
        echo "BUILD_TIMESTAMP $(date +%s)"
        EOF
        chmod +x tools/workspace_status.sh

        # Verify build environment
        echo "Current directory: $(pwd)"
        ls -l tools/

        ./build_shusky.sh --verbose_failures

    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: kernel-artifacts
        path: |
          kernel_devices_google_shusky/out/mixed/dist/*
          kernel_devices_google_shusky/bazel-bin/**/*.ko
          kernel_devices_google_shusky/bazel-bin/**/*.img
