name: Build Shusky Kernel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Installiere benötigte Pakete
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg zip unzip git build-essential bison flex libssl-dev bc wget software-properties-common apt-transport-https

          # Versuche zuerst den Bazel Keyring zu aktualisieren
          sudo apt-key update --keyring /usr/share/keyrings/bazel-archive-keyring.gpg

          # Falls das Update fehlschlägt, überprüfe die Internetverbindung
          if [ $? -eq 1 ]; then
            echo "## Überprüfung der Internetverbindung"
            ping -c 3 apt.bazel.build
          fi

      - name: Führe den Rest des Skripts aus (angepasst, falls nötig)
        # ... rest of the steps from your previous code ...

