name: Build Pixel 8 Pro Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl zip unzip git python3

    - name: Install Bazel
      run: |
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
        sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt-get update
        sudo apt-get install -y bazel

    - name: Setup Build Environment
      run: |
        WORKSPACE_DIR=$(pwd)
        echo "Current directory: $WORKSPACE_DIR"
        mkdir -p tools
        BAZEL_PATH=$(which bazel)
        echo "Bazel path: $BAZEL_PATH"
        sudo cp "$BAZEL_PATH" tools/bazel
        sudo chmod +x tools/bazel
        echo "Tools directory contents:"
        ls -la tools/
        echo "Adding tools to PATH"
        echo "PATH=$WORKSPACE_DIR/tools:$PATH" >> $GITHUB_ENV
        echo "Verifying bazel in tools:"
        tools/bazel --version

    - name: Prepare Kernel Source
      run: |
        echo "Current directory before clone: $(pwd)"
        echo "Saving tools directory"
        mv tools tools_backup
        rm -rf * .[!.]*
        echo "Restoring tools directory"
        mv tools_backup tools
        echo "Cloning kernel source"
        git clone https://gitlab.hentaios.com/hentaios-gs-6.x/kernel_devices_google_shusky.git .
        git checkout Vallhound
        git submodule update --init --recursive
        echo "Final directory structure:"
        ls -la
        echo "Tools directory contents:"
        ls -la tools/

    - name: Build Kernel
      run: |
        echo "Current directory: $(pwd)"
        echo "PATH: $PATH"
        echo "Tools directory contents:"
        ls -la tools/
        chmod +x build_shusky.sh
        ./build_shusky.sh

    - name: Upload Kernel Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-artifacts
        path: |
          out/mixed/dist/*
          bazel-bin/**/*.ko
          bazel-bin/**/*.img
