name: Zuma Pro
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: write   # Allows triggering actions

on:
  workflow_call:  # This allows this workflow to be called from another workflow
  
jobs:
  build-kernel-sultan-kernelsu-susfs:
    uses: ./.github/workflows/sultan.yml
    secrets: inherit
    with:
      codename: "zumapro"
      repo: "android_kernel_google_zumapro"
      android_version: "android14"
      kernel_version: "6.1"
